### ISSUE TITLE
AWS Managed Prometheus support

### ISSUE THREAD

**Issue by mpostument** [densify-dev/helm-charts#7]
Hello, we are using AWS Managed prometheus, to access which there is required AWS role to be associated with kubernetes service account. But currently helm chart do not support additional annotations.  

Example of annotation:

```yaml
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::${awsAccountId}:role/${role_name}
```

Also AWS SigV4 is required to be able to authenticate. Does densify support AWS Sigv4?

Example with sigv4 and grafana https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-query-standalone-grafana.html

**Comment by mpostument** [comment]
This should cover annotations part https://github.com/densify-dev/helm-charts/pull/8. But sigv4 is still needed

**Comment by tsipo** [comment]
Hello @mpostument , thank you for opening this issue and for your PR. We at Densify will be reviewing it.

**Comment by tsipo** [comment]
Issue fixed:

1. [Merged PR](https://github.com/densify-dev/helm-charts/commit/0f7e63062c04c39ed29cc86f0aaa3bff34e65c8e)
2. Container data collection [v4](https://github.com/densify-dev/container-data-collection/releases/tag/v4.0.0) release - multi-cluster support, Sigv4 support and other features
3. Updated the Helm chart to v4: [here](https://github.com/densify-dev/helm-charts/commit/b10dd2e92d381df215d61b211a5536c10f7acc10) and [here](https://github.com/densify-dev/helm-charts/commit/fd5327785e7e2ff56aabb9a41bdd6fa30e75b1ed)
